"""Learning mode synthesizer: generate draft capability manifests from observations.

Synthesis rules per DESIGN.md 7.5:
- Observed tools get 'allow' with conditions narrowed to observed arg patterns.
- Unobserved tools get the wildcard deny.
- Write-class tools on trifecta-complete servers get 'approve' regardless.
- Output is clearly marked as a draft.
"""

from __future__ import annotations

import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import yaml

from bawbel_gate._const import (
    EFFECT_ALLOW,
    EFFECT_APPROVE,
    EFFECT_DENY,
    SCHEMA_CAPABILITY_MANIFEST_V1,
)

# Tools whose names suggest write operations — get 'approve' on trifecta servers
_WRITE_KEYWORDS = frozenset({
    "create", "update", "write", "delete", "push", "post", "put",
    "patch", "merge", "send", "publish", "commit",
})

_DRAFT_BANNER = (
    "# DRAFT MANIFEST — generated by 'bawbel-gate learn synthesize'\n"
    "# Review every grant before enforcing. This is NOT policy.\n"
    "# See DESIGN.md 7.5 for synthesis rules.\n\n"
)


def synthesize_manifests(obs_path: Path, out_dir: Path) -> list[Path]:
    """Generate one draft manifest per server observed. Return paths written."""
    observations = _load(obs_path)
    if not observations:
        print("No observations to synthesize.", file=sys.stderr)
        return []

    by_server: dict[str, list[dict]] = defaultdict(list)
    for obs in observations:
        by_server[obs["server"]].append(obs)

    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for server, tools in sorted(by_server.items()):
        manifest = _build_manifest(server, tools)
        dest = out_dir / f"{server}.cap.yaml"
        content = _DRAFT_BANNER + yaml.dump(manifest, default_flow_style=False, sort_keys=False)
        dest.write_text(content, encoding="utf-8")
        print(f"wrote {dest}  ({len(tools)} allow grants, wildcard deny)")
        written.append(dest)

    print("\nNOTE: synthesized manifests set trifecta flags conservatively.")
    print("Review before enforcing. `learn synthesize` output is a draft, not a policy.")
    return written


def _build_manifest(server: str, tools: list[dict]) -> dict[str, Any]:
    grants_tools = []
    for tool_obs in sorted(tools, key=lambda t: t["tool"]):
        effect = _pick_effect(server, tool_obs["tool"])
        grant: dict[str, Any] = {"name": tool_obs["tool"], "effect": effect}
        conditions = _infer_conditions(tool_obs)
        if conditions:
            grant["conditions"] = conditions
        grants_tools.append(grant)

    grants_tools.append({"name": "*", "effect": EFFECT_DENY})

    return {
        "schema": SCHEMA_CAPABILITY_MANIFEST_V1,
        "subject": {
            "kind": "mcp-server",
            "name": server,
            "transport": "stdio",
        },
        "provenance_class": f"tool.response.{server}",
        "instruction_authority": "none",
        "trifecta": {
            "private_data": True,
            "untrusted_content": True,
            "external_comms": True,
        },
        "grants": {
            "tools": grants_tools,
            "argument_guards": [
                {"applies_to": "*", "outbound_secret_scan": True, "max_outbound_bytes": 65536}
            ],
        },
        "taint_rules": [
            {
                "when": {"tainted_by_any": [f"tool.response.{server}"]},
                "then": [{"tools_with": "external_comms", "effect": EFFECT_APPROVE}],
            }
        ],
        "integrity_watch": [
            {"kind": "tool_schema", "on_drift": "suspend"}
        ],
    }


def _pick_effect(server: str, tool: str) -> str:
    tool_lower = tool.lower()
    if any(kw in tool_lower for kw in _WRITE_KEYWORDS):
        return EFFECT_APPROVE
    return EFFECT_ALLOW


def _infer_conditions(tool_obs: dict) -> dict[str, Any]:
    """Narrow conditions from observed arg prefixes where safe generalisations exist."""
    conditions: dict[str, Any] = {}
    prefixes_by_path: dict[str, list[str]] = defaultdict(list)
    for a in tool_obs.get("arg_observations", []):
        if a["value_type"] == "str" and a["sample_prefix"]:
            prefixes_by_path[a["arg_path"]].append(a["sample_prefix"])

    for path, samples in prefixes_by_path.items():
        common = _common_prefix(samples)
        if common and len(common) >= 3:
            conditions[f"args.{path}"] = {"pattern": f"{common}*"}
    return conditions


def _common_prefix(strings: list[str]) -> str:
    if not strings:
        return ""
    prefix = strings[0]
    for s in strings[1:]:
        while not s.startswith(prefix):
            prefix = prefix[:-1]
            if not prefix:
                return ""
    return prefix


def _load(path: Path) -> list[dict]:
    if not path.exists():
        return []
    records = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            records.append(json.loads(line))
    return records
